CREATE TABLE livro (
    id SERIAL PRIMARY KEY,
    titulo VARCHAR(255) NOT NULL,
    autor_id INTEGER NOT NULL REFERENCES autor(id),
    status VARCHAR(50) NOT NULL DEFAULT 'DISPONIVEL' CHECK ( status IN ('DISPONIVEL', 'INDISPONIVEL')),
    data_cadastro TIMESTAMP NOT NULL DEFAULT NOW(),
    data_atualizacao TIMESTAMP NOT NULL DEFAULT NOW()
)
